services:
  db:
    platform: linux/amd64
    image: postgis/postgis:15-3.5 
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: psql
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
      - ./data:/data:ro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://psql:password@db:5432/mydatabase
    depends_on:
      - db
    ports:
      - "8000:8000"
volumes:
  pgdata:
